### PR TITLE
8316424: [Lilliput/JDK21] ZGC/CDS-related test fixes

### PR DESCRIPTION
**Pull request by rkennke**
A few tests with ZGC and CDS are failing. Reason is that we disable COH with single-gen-ZGC but not with gen-ZGC, and some tests dump with one and run with the other. This causes unexpected mismatches.

Testing:
 - [x] runtime/cds/appcds/TestZGCWithCDS.java (default)
 - [x] runtime/cds/appcds/TestZGCWithCDS.java (+UCOH)
 - [x] runtime/cds/appcds/TestZGCWithCDS.java (-UCOH)
 - [x] runtime/cds/appcds/loaderConstraints/DynamicLoaderConstraintsTest.java (default)
 - [x] runtime/cds/appcds/loaderConstraints/DynamicLoaderConstraintsTest.java (+UCOH)
 - [x] runtime/cds/appcds/loaderConstraints/DynamicLoaderConstraintsTest.java (-UCOH)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8316424](https://bugs.openjdk.org/browse/JDK-8316424): [Lilliput/JDK21] ZGC/CDS-related test fixes (**Enhancement** - P4)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/lilliput-jdk21u.git pull/7/head:pull/7` \
`$ git checkout pull/7`

Update a local copy of the PR: \
`$ git checkout pull/7` \
`$ git pull https://git.openjdk.org/lilliput-jdk21u.git pull/7/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7`

View PR using the GUI difftool: \
`$ git pr show -t 7`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/lilliput-jdk21u/pull/7.diff">https://git.openjdk.org/lilliput-jdk21u/pull/7.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/lilliput-jdk21u/pull/7#issuecomment-1723357626)

### CODE REVIEW

**Review by shipilev — COMMENTED** [review]
Would it make more sense to sense `+UCOH` in `VMProps.java` and put appropriate `@requires` in `+ZGenerational` `@run` block?

**Comment by rkennke** [comment]
> Would it make more sense to sense `+UCOH` in `VMProps.java` and put appropriate `@requires` in `+ZGenerational` `@run` block?

No, I don't think so. The two affected tests spawn new JVMs and ignore the test options - at least sometimes (e.g. when dumping CDS).

**Review by shipilev — APPROVED** [review]
All right then.

**Pull request closed without merging**
